# Generated by Django 5.2.10 on 2026-01-11 08:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('content_html', models.TextField(blank=True)),
                ('content_text', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'email_signatures',
                'ordering': ['-is_default', 'name'],
                'unique_together': {('workspace', 'name')},
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=500)),
                ('content_html', models.TextField()),
                ('content_text', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('outreach', 'Cold Outreach'), ('followup', 'Follow-up'), ('nurture', 'Nurture'), ('promotional', 'Promotional'), ('transactional', 'Transactional'), ('other', 'Other')], default='outreach', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('include_signature', models.BooleanField(default=True)),
                ('variables', models.JSONField(blank=True, default=list)),
                ('has_spintax', models.BooleanField(default=False)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('is_shared', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
                ('signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='campaigns.emailsignature')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'email_templates',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SnippetLibrary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('shortcode', models.CharField(max_length=50)),
                ('content_html', models.TextField()),
                ('content_text', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'snippet_library',
                'ordering': ['category', 'name'],
                'unique_together': {('workspace', 'shortcode')},
            },
        ),
        migrations.CreateModel(
            name='TemplateFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='campaigns.templatefolder')),
                ('templates', models.ManyToManyField(blank=True, related_name='folders', to='campaigns.emailtemplate')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_folders', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'template_folders',
                'ordering': ['name'],
                'unique_together': {('workspace', 'name', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='TemplateVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('subject', models.CharField(max_length=500)),
                ('content_html', models.TextField()),
                ('content_text', models.TextField(blank=True)),
                ('change_notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_versions', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='campaigns.emailtemplate')),
            ],
            options={
                'db_table': 'template_versions',
                'ordering': ['-version_number'],
                'unique_together': {('template', 'version_number')},
            },
        ),
    ]
