# Generated by Django 5.2.10 on 2026-01-11 13:30

import apps.tracking.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0002_campaign_abtestvariant_campaignlog_campaignrecipient_and_more'),
        ('contacts', '0002_scoredecayconfig_scoringrule_scorethreshold_and_more'),
        ('email_accounts', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(default=apps.tracking.models.generate_token, max_length=64, unique=True)),
                ('original_url', models.URLField(max_length=2048)),
                ('click_count', models.IntegerField(default=0)),
                ('first_clicked_at', models.DateTimeField(blank=True, null=True)),
                ('last_clicked_at', models.DateTimeField(blank=True, null=True)),
                ('campaign_recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_links', to='campaigns.campaignrecipient')),
            ],
            options={
                'db_table': 'tracking_links',
            },
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('open', 'Email Opened'), ('click', 'Link Clicked'), ('unsubscribe', 'Unsubscribed'), ('bounce', 'Bounced'), ('complaint', 'Spam Complaint'), ('delivery', 'Delivered')], max_length=20)),
                ('clicked_url', models.URLField(blank=True, max_length=2048)),
                ('bounce_type', models.CharField(blank=True, choices=[('hard', 'Hard Bounce'), ('soft', 'Soft Bounce'), ('complaint', 'Complaint')], max_length=20)),
                ('bounce_code', models.CharField(blank=True, max_length=10)),
                ('bounce_message', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('device_brand', models.CharField(blank=True, max_length=100)),
                ('device_model', models.CharField(blank=True, max_length=100)),
                ('browser_name', models.CharField(blank=True, max_length=100)),
                ('browser_version', models.CharField(blank=True, max_length=50)),
                ('os_name', models.CharField(blank=True, max_length=100)),
                ('os_version', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('country_code', models.CharField(blank=True, max_length=10)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50)),
                ('is_bot', models.BooleanField(default=False)),
                ('bot_name', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('campaign_recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='campaigns.campaignrecipient')),
                ('tracking_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='tracking.trackinglink')),
            ],
            options={
                'db_table': 'tracking_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackingPixel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(default=apps.tracking.models.generate_token, max_length=64, unique=True)),
                ('open_count', models.IntegerField(default=0)),
                ('first_opened_at', models.DateTimeField(blank=True, null=True)),
                ('last_opened_at', models.DateTimeField(blank=True, null=True)),
                ('campaign_recipient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_pixel', to='campaigns.campaignrecipient')),
            ],
            options={
                'db_table': 'tracking_pixels',
            },
        ),
        migrations.CreateModel(
            name='UnsubscribeToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(default=apps.tracking.models.generate_token, max_length=64, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unsubscribe_tokens', to='campaigns.campaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unsubscribe_tokens', to='contacts.contact')),
            ],
            options={
                'db_table': 'unsubscribe_tokens',
            },
        ),
        migrations.CreateModel(
            name='BounceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('bounce_type', models.CharField(choices=[('hard', 'Hard Bounce'), ('soft', 'Soft Bounce')], max_length=20)),
                ('bounce_category', models.CharField(choices=[('invalid', 'Invalid Address'), ('mailbox_full', 'Mailbox Full'), ('blocked', 'Blocked'), ('content', 'Content Blocked'), ('timeout', 'Connection Timeout'), ('other', 'Other')], default='other', max_length=20)),
                ('bounce_code', models.CharField(blank=True, max_length=10)),
                ('bounce_message', models.TextField(blank=True)),
                ('message_id', models.CharField(blank=True, max_length=255)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bounce_records', to='campaigns.campaign')),
                ('campaign_recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bounce_records', to='campaigns.campaignrecipient')),
                ('email_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bounce_records', to='email_accounts.emailaccount')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bounce_records', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'bounce_records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='bounce_reco_email_45213a_idx'), models.Index(fields=['workspace', '-created_at'], name='bounce_reco_workspa_657ab1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ComplaintRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('complaint_type', models.CharField(choices=[('spam', 'Marked as Spam'), ('abuse', 'Abuse Report'), ('other', 'Other')], default='spam', max_length=20)),
                ('feedback_id', models.CharField(blank=True, max_length=255)),
                ('message_id', models.CharField(blank=True, max_length=255)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint_records', to='campaigns.campaign')),
                ('campaign_recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint_records', to='campaigns.campaignrecipient')),
                ('email_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint_records', to='email_accounts.emailaccount')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_records', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'complaint_records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='complaint_r_email_efd130_idx'), models.Index(fields=['workspace', '-created_at'], name='complaint_r_workspa_37c544_idx')],
            },
        ),
        migrations.CreateModel(
            name='SuppressionList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('reason', models.CharField(choices=[('hard_bounce', 'Hard Bounce'), ('complaint', 'Spam Complaint'), ('unsubscribe', 'Unsubscribed'), ('manual', 'Manually Added')], max_length=20)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppression_list', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'suppression_list',
                'ordering': ['-created_at'],
                'unique_together': {('workspace', 'email')},
            },
        ),
        migrations.CreateModel(
            name='TrackingDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('ssl_enabled', models.BooleanField(default=True)),
                ('verification_token', models.CharField(default=apps.tracking.models.generate_token, max_length=64)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_domains', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'tracking_domains',
                'unique_together': {('workspace', 'domain')},
            },
        ),
        migrations.AddIndex(
            model_name='trackinglink',
            index=models.Index(fields=['token'], name='tracking_li_token_cf9afd_idx'),
        ),
        migrations.AddIndex(
            model_name='trackinglink',
            index=models.Index(fields=['campaign_recipient'], name='tracking_li_campaig_d4702d_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingevent',
            index=models.Index(fields=['event_type', '-created_at'], name='tracking_ev_event_t_a6d10a_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingevent',
            index=models.Index(fields=['campaign_recipient', '-created_at'], name='tracking_ev_campaig_fd6c31_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingevent',
            index=models.Index(fields=['ip_address'], name='tracking_ev_ip_addr_da097c_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingevent',
            index=models.Index(fields=['-created_at'], name='tracking_ev_created_48dd54_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingpixel',
            index=models.Index(fields=['token'], name='tracking_pi_token_cd16ee_idx'),
        ),
        migrations.AddIndex(
            model_name='unsubscribetoken',
            index=models.Index(fields=['token'], name='unsubscribe_token_7f67b9_idx'),
        ),
        migrations.AddIndex(
            model_name='unsubscribetoken',
            index=models.Index(fields=['contact'], name='unsubscribe_contact_bb3506_idx'),
        ),
    ]
