# Generated by Django 5.2.10 on 2026-01-11 14:02

import apps.tracking.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_scoredecayconfig_scoringrule_scorethreshold_and_more'),
        ('tracking', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('entry_page', models.URLField(max_length=2048)),
                ('referrer', models.URLField(blank=True, max_length=2048)),
                ('exit_page', models.URLField(blank=True, max_length=2048)),
                ('utm_source', models.CharField(blank=True, max_length=255)),
                ('utm_medium', models.CharField(blank=True, max_length=255)),
                ('utm_campaign', models.CharField(blank=True, max_length=255)),
                ('page_views', models.IntegerField(default=0)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('max_scroll_depth', models.IntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'visitor_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteTrackingScript',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('script_id', models.CharField(default=apps.tracking.models.generate_token, max_length=32, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('track_page_views', models.BooleanField(default=True)),
                ('track_clicks', models.BooleanField(default=True)),
                ('track_forms', models.BooleanField(default=False)),
                ('track_scroll_depth', models.BooleanField(default=False)),
                ('track_time_on_page', models.BooleanField(default=True)),
                ('allowed_domains', models.TextField(default='*')),
                ('award_score_on_visit', models.BooleanField(default=True)),
                ('visit_score_points', models.IntegerField(default=5)),
                ('page_view_score_points', models.IntegerField(default=1)),
                ('session_timeout_minutes', models.IntegerField(default=30)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_script', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'website_tracking_scripts',
            },
        ),
        migrations.CreateModel(
            name='WebsiteVisitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visitor_id', models.CharField(db_index=True, max_length=64)),
                ('is_identified', models.BooleanField(default=False)),
                ('identified_at', models.DateTimeField(blank=True, null=True)),
                ('identification_method', models.CharField(blank=True, max_length=50)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('first_page_url', models.URLField(blank=True, max_length=2048)),
                ('first_referrer', models.URLField(blank=True, max_length=2048)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('last_page_url', models.URLField(blank=True, max_length=2048)),
                ('utm_source', models.CharField(blank=True, max_length=255)),
                ('utm_medium', models.CharField(blank=True, max_length=255)),
                ('utm_campaign', models.CharField(blank=True, max_length=255)),
                ('utm_term', models.CharField(blank=True, max_length=255)),
                ('utm_content', models.CharField(blank=True, max_length=255)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('browser_name', models.CharField(blank=True, max_length=100)),
                ('browser_version', models.CharField(blank=True, max_length=50)),
                ('os_name', models.CharField(blank=True, max_length=100)),
                ('os_version', models.CharField(blank=True, max_length=50)),
                ('screen_resolution', models.CharField(blank=True, max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('country_code', models.CharField(blank=True, max_length=10)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('timezone', models.CharField(blank=True, max_length=50)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('company_domain', models.CharField(blank=True, max_length=255)),
                ('company_industry', models.CharField(blank=True, max_length=255)),
                ('company_size', models.CharField(blank=True, max_length=50)),
                ('total_sessions', models.IntegerField(default=0)),
                ('total_page_views', models.IntegerField(default=0)),
                ('total_time_on_site', models.IntegerField(default=0)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_visitors', to='contacts.contact')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_visitors', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'website_visitors',
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('click', 'Click'), ('form_submit', 'Form Submit'), ('form_start', 'Form Start'), ('scroll', 'Scroll'), ('video_play', 'Video Play'), ('video_complete', 'Video Complete'), ('download', 'Download'), ('outbound_link', 'Outbound Link'), ('custom', 'Custom Event')], max_length=30)),
                ('event_name', models.CharField(blank=True, max_length=100)),
                ('page_url', models.URLField(max_length=2048)),
                ('page_path', models.CharField(max_length=2048)),
                ('element_id', models.CharField(blank=True, max_length=255)),
                ('element_class', models.CharField(blank=True, max_length=255)),
                ('element_text', models.CharField(blank=True, max_length=512)),
                ('target_url', models.URLField(blank=True, max_length=2048)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tracking.visitorsession')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tracking.websitevisitor')),
            ],
            options={
                'db_table': 'website_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='visitorsession',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='tracking.websitevisitor'),
        ),
        migrations.CreateModel(
            name='VisitorIdentification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('email_link', 'Email Link Click'), ('form_submit', 'Form Submission'), ('api', 'API Call'), ('manual', 'Manual Identification'), ('ip_match', 'IP Address Match')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_identifications', to='contacts.contact')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifications', to='tracking.websitevisitor')),
            ],
            options={
                'db_table': 'visitor_identifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_url', models.URLField(max_length=2048)),
                ('page_path', models.CharField(max_length=2048)),
                ('page_title', models.CharField(blank=True, max_length=512)),
                ('referrer', models.URLField(blank=True, max_length=2048)),
                ('time_on_page', models.IntegerField(default=0)),
                ('scroll_depth', models.IntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_view_events', to='tracking.visitorsession')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='tracking.websitevisitor')),
            ],
            options={
                'db_table': 'page_views',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='websitevisitor',
            index=models.Index(fields=['workspace', 'is_identified'], name='website_vis_workspa_6fd897_idx'),
        ),
        migrations.AddIndex(
            model_name='websitevisitor',
            index=models.Index(fields=['workspace', '-last_seen_at'], name='website_vis_workspa_02bf6c_idx'),
        ),
        migrations.AddIndex(
            model_name='websitevisitor',
            index=models.Index(fields=['contact'], name='website_vis_contact_aed69a_idx'),
        ),
        migrations.AddIndex(
            model_name='websitevisitor',
            index=models.Index(fields=['ip_address'], name='website_vis_ip_addr_0fa40c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='websitevisitor',
            unique_together={('workspace', 'visitor_id')},
        ),
        migrations.AddIndex(
            model_name='websiteevent',
            index=models.Index(fields=['visitor', '-created_at'], name='website_eve_visitor_69493c_idx'),
        ),
        migrations.AddIndex(
            model_name='websiteevent',
            index=models.Index(fields=['session'], name='website_eve_session_15ae8e_idx'),
        ),
        migrations.AddIndex(
            model_name='websiteevent',
            index=models.Index(fields=['event_type', '-created_at'], name='website_eve_event_t_6accfd_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorsession',
            index=models.Index(fields=['visitor', '-started_at'], name='visitor_ses_visitor_20a538_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorsession',
            index=models.Index(fields=['session_id'], name='visitor_ses_session_a01836_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['visitor', '-created_at'], name='page_views_visitor_7b6ef7_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['session'], name='page_views_session_108156_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['page_path'], name='page_views_page_pa_d68cfd_idx'),
        ),
    ]
