# Generated by Django 5.2.10 on 2026-01-11 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('workspaces', '0002_workspace_company_name_workspace_company_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_users', to='workspaces.workspace'),
        ),
    ]
