# Generated by Django 5.2.10 on 2026-01-11 07:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('company', models.CharField(blank=True, default='', max_length=200)),
                ('job_title', models.CharField(blank=True, default='', max_length=200)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('website', models.URLField(blank=True, default='')),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('twitter_handle', models.CharField(blank=True, default='', max_length=50)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('timezone', models.CharField(blank=True, default='', max_length=50)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('unsubscribed', 'Unsubscribed'), ('bounced', 'Bounced'), ('complained', 'Complained')], default='active', max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('score_updated_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, default='', max_length=100)),
                ('source_details', models.JSONField(blank=True, default=dict)),
                ('emails_sent', models.IntegerField(default=0)),
                ('emails_opened', models.IntegerField(default=0)),
                ('emails_clicked', models.IntegerField(default=0)),
                ('emails_replied', models.IntegerField(default=0)),
                ('emails_bounced', models.IntegerField(default=0)),
                ('last_emailed_at', models.DateTimeField(blank=True, null=True)),
                ('last_opened_at', models.DateTimeField(blank=True, null=True)),
                ('last_clicked_at', models.DateTimeField(blank=True, null=True)),
                ('last_replied_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribe_reason', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('list_type', models.CharField(choices=[('static', 'Static List'), ('smart', 'Smart List')], default='static', max_length=20)),
                ('filter_criteria', models.JSONField(blank=True, default=dict)),
                ('contact_count', models.IntegerField(default=0)),
                ('last_count_updated_at', models.DateTimeField(blank=True, null=True)),
                ('contacts', models.ManyToManyField(blank=True, related_name='lists', to='contacts.contact')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_lists', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'workspace')},
            },
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('csv', 'CSV'), ('excel', 'Excel'), ('json', 'JSON')], max_length=20)),
                ('file_path', models.CharField(max_length=500)),
                ('field_mapping', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_rows', models.IntegerField(default=0)),
                ('processed_rows', models.IntegerField(default=0)),
                ('created_count', models.IntegerField(default=0)),
                ('updated_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('default_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.contactlist')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='workspaces.workspace')),
                ('default_tags', models.ManyToManyField(blank=True, to='contacts.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='contacts', to='contacts.tag'),
        ),
        migrations.CreateModel(
            name='ContactActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(choices=[('email_sent', 'Email Sent'), ('email_opened', 'Email Opened'), ('email_clicked', 'Email Clicked'), ('email_replied', 'Email Replied'), ('email_bounced', 'Email Bounced'), ('unsubscribed', 'Unsubscribed'), ('complained', 'Complained'), ('score_changed', 'Score Changed'), ('tag_added', 'Tag Added'), ('tag_removed', 'Tag Removed'), ('list_added', 'Added to List'), ('list_removed', 'Removed from List'), ('field_updated', 'Field Updated'), ('page_viewed', 'Page Viewed')], max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('campaign_id', models.UUIDField(blank=True, null=True)),
                ('sequence_id', models.UUIDField(blank=True, null=True)),
                ('email_id', models.UUIDField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='contacts.contact')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['contact', '-created_at'], name='contacts_co_contact_13797b_idx'), models.Index(fields=['contact', 'activity_type'], name='contacts_co_contact_8f6deb_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('field_key', models.SlugField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean'), ('select', 'Select'), ('multiselect', 'Multi-Select'), ('url', 'URL'), ('email', 'Email')], default='text', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('is_required', models.BooleanField(default=False)),
                ('default_value', models.CharField(blank=True, default='', max_length=500)),
                ('options', models.JSONField(blank=True, default=list)),
                ('display_order', models.IntegerField(default=0)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'unique_together': {('workspace', 'field_key')},
            },
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['email'], name='contacts_co_email_25f973_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['workspace', 'status'], name='contacts_co_workspa_bd58fd_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['workspace', 'score'], name='contacts_co_workspa_4053f4_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['workspace', '-created_at'], name='contacts_co_workspa_a106f7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('email', 'workspace')},
        ),
    ]
