# Generated by Django 5.2.10 on 2026-01-11 13:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreDecayConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('decay_points', models.IntegerField(default=5)),
                ('decay_interval_days', models.IntegerField(default=30)),
                ('min_score', models.IntegerField(default=0)),
                ('inactivity_days', models.IntegerField(default=30)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_decay_config', to='workspaces.workspace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScoringRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('event_type', models.CharField(choices=[('email_opened', 'Email Opened'), ('email_clicked', 'Email Clicked'), ('email_replied', 'Email Replied'), ('link_clicked', 'Link Clicked'), ('page_viewed', 'Page Viewed'), ('form_submitted', 'Form Submitted'), ('tag_added', 'Tag Added'), ('list_added', 'Added to List'), ('custom', 'Custom Event')], max_length=30)),
                ('conditions', models.JSONField(blank=True, default=list)),
                ('score_change', models.IntegerField(default=0)),
                ('max_applications', models.IntegerField(blank=True, null=True)),
                ('cooldown_hours', models.IntegerField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_rules', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScoreThreshold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classification', models.CharField(choices=[('hot', 'Hot Lead'), ('warm', 'Warm Lead'), ('cold', 'Cold Lead'), ('frozen', 'Frozen')], max_length=20)),
                ('min_score', models.IntegerField()),
                ('max_score', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_thresholds', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-min_score'],
                'unique_together': {('workspace', 'classification')},
            },
        ),
        migrations.CreateModel(
            name='ScoreHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_score', models.IntegerField()),
                ('new_score', models.IntegerField()),
                ('score_change', models.IntegerField()),
                ('reason', models.CharField(max_length=200)),
                ('event_type', models.CharField(blank=True, default='', max_length=30)),
                ('event_data', models.JSONField(blank=True, default=dict)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_history', to='contacts.contact')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='contacts.scoringrule')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['contact', '-created_at'], name='contacts_sc_contact_815f88_idx')],
            },
        ),
    ]
