# Generated by Django 5.2.10 on 2026-01-11 14:18

import apps.webhooks.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(max_length=2048)),
                ('events', models.JSONField(default=list, help_text='List of event types this webhook subscribes to')),
                ('secret', models.CharField(default=apps.webhooks.models.generate_webhook_secret, max_length=64)),
                ('verify_ssl', models.BooleanField(default=True)),
                ('headers', models.JSONField(blank=True, default=dict, help_text='Custom headers to include with webhook requests')),
                ('is_active', models.BooleanField(default=True)),
                ('timeout_seconds', models.IntegerField(default=30)),
                ('max_retries', models.IntegerField(default=5)),
                ('retry_delay_seconds', models.IntegerField(default=60)),
                ('total_deliveries', models.IntegerField(default=0)),
                ('successful_deliveries', models.IntegerField(default=0)),
                ('failed_deliveries', models.IntegerField(default=0)),
                ('last_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('consecutive_failures', models.IntegerField(default=0)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_webhooks', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'webhooks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=50)),
                ('event_id', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField()),
                ('request_headers', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('response_status_code', models.IntegerField(blank=True, null=True)),
                ('response_headers', models.JSONField(blank=True, default=dict)),
                ('response_body', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_number', models.IntegerField(default=1)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='webhooks.webhook')),
            ],
            options={
                'db_table': 'webhook_deliveries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEventLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_id', models.CharField(max_length=64, unique=True)),
                ('event_type', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
                ('contact_id', models.UUIDField(blank=True, null=True)),
                ('campaign_id', models.UUIDField(blank=True, null=True)),
                ('sequence_id', models.UUIDField(blank=True, null=True)),
                ('webhooks_triggered', models.IntegerField(default=0)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'webhook_event_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('key_prefix', models.CharField(default=apps.webhooks.models.generate_api_key_prefix, max_length=8)),
                ('key_hash', models.CharField(max_length=64, unique=True)),
                ('permission', models.CharField(choices=[('read', 'Read Only'), ('write', 'Read & Write'), ('admin', 'Full Access')], default='read', max_length=10)),
                ('allowed_ips', models.TextField(blank=True, help_text='Comma-separated list of allowed IPs')),
                ('rate_limit_per_minute', models.IntegerField(default=60)),
                ('rate_limit_per_day', models.IntegerField(default=10000)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('total_requests', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_keys', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'api_keys',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['key_prefix'], name='api_keys_key_pre_9c2634_idx'), models.Index(fields=['workspace', 'is_active'], name='api_keys_workspa_dc6b0c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='webhook',
            index=models.Index(fields=['workspace', 'is_active'], name='webhooks_workspa_fe3064_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['webhook', '-created_at'], name='webhook_del_webhook_b549ed_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['status', 'next_retry_at'], name='webhook_del_status_741062_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['event_id'], name='webhook_del_event_i_bd4e29_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookeventlog',
            index=models.Index(fields=['workspace', '-created_at'], name='webhook_eve_workspa_d7b22e_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookeventlog',
            index=models.Index(fields=['event_type', '-created_at'], name='webhook_eve_event_t_f2e99e_idx'),
        ),
    ]
