# Generated by Django 5.2.10 on 2026-01-11 15:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='workspace',
            name='company_website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='default_reply_to',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='workspace',
            name='primary_color',
            field=models.CharField(default='#3B82F6', max_length=7),
        ),
        migrations.AddField(
            model_name='workspaceinvitation',
            name='message',
            field=models.TextField(blank=True, help_text='Personal message to include in invitation email'),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='daily_digest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='workspaceinvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='WorkspaceActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('workspace_created', 'Workspace Created'), ('workspace_updated', 'Workspace Updated'), ('workspace_deleted', 'Workspace Deleted'), ('member_invited', 'Member Invited'), ('member_joined', 'Member Joined'), ('member_left', 'Member Left'), ('member_removed', 'Member Removed'), ('member_role_changed', 'Member Role Changed'), ('invitation_revoked', 'Invitation Revoked'), ('campaign_created', 'Campaign Created'), ('campaign_started', 'Campaign Started'), ('campaign_paused', 'Campaign Paused'), ('campaign_completed', 'Campaign Completed'), ('campaign_deleted', 'Campaign Deleted'), ('sequence_created', 'Sequence Created'), ('sequence_activated', 'Sequence Activated'), ('sequence_paused', 'Sequence Paused'), ('sequence_deleted', 'Sequence Deleted'), ('contacts_imported', 'Contacts Imported'), ('contacts_exported', 'Contacts Exported'), ('contacts_deleted', 'Contacts Deleted'), ('integration_connected', 'Integration Connected'), ('integration_disconnected', 'Integration Disconnected'), ('settings_updated', 'Settings Updated'), ('api_key_created', 'API Key Created'), ('api_key_revoked', 'API Key Revoked'), ('webhook_created', 'Webhook Created'), ('webhook_deleted', 'Webhook Deleted')], max_length=50)),
                ('description', models.TextField()),
                ('target_type', models.CharField(blank=True, max_length=50)),
                ('target_id', models.CharField(blank=True, max_length=36)),
                ('target_name', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_activities', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_activities', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'workspace_activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', '-created_at'], name='workspace_a_workspa_78531c_idx'), models.Index(fields=['user', '-created_at'], name='workspace_a_user_id_7eade8_idx'), models.Index(fields=['action', '-created_at'], name='workspace_a_action_ea9f56_idx')],
            },
        ),
    ]
