# Generated by Django 5.2.10 on 2026-01-11 14:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('integration_type', models.CharField(choices=[('slack', 'Slack'), ('discord', 'Discord'), ('hubspot', 'HubSpot'), ('salesforce', 'Salesforce'), ('google_sheets', 'Google Sheets'), ('zapier', 'Zapier'), ('n8n', 'n8n'), ('custom_webhook', 'Custom Webhook')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Error'), ('pending', 'Pending Setup')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(default=dict)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('total_syncs', models.IntegerField(default=0)),
                ('successful_syncs', models.IntegerField(default=0)),
                ('failed_syncs', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_integrations', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'integrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HubSpotIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portal_id', models.CharField(blank=True, max_length=50)),
                ('portal_name', models.CharField(blank=True, max_length=100)),
                ('sync_direction', models.CharField(choices=[('to_hubspot', 'ColdMail → HubSpot'), ('from_hubspot', 'HubSpot → ColdMail'), ('bidirectional', 'Bidirectional')], default='to_hubspot', max_length=20)),
                ('sync_contacts', models.BooleanField(default=True)),
                ('sync_companies', models.BooleanField(default=False)),
                ('sync_deals', models.BooleanField(default=False)),
                ('sync_activities', models.BooleanField(default=True)),
                ('auto_sync_interval', models.IntegerField(default=60)),
                ('last_auto_sync', models.DateTimeField(blank=True, null=True)),
                ('field_mapping', models.JSONField(default=dict)),
                ('sync_only_hot_leads', models.BooleanField(default=False)),
                ('min_score_to_sync', models.IntegerField(default=0)),
                ('integration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hubspot_config', to='integrations.integration')),
            ],
            options={
                'db_table': 'hubspot_integrations',
            },
        ),
        migrations.CreateModel(
            name='GoogleSheetsIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spreadsheet_id', models.CharField(blank=True, max_length=100)),
                ('spreadsheet_name', models.CharField(blank=True, max_length=200)),
                ('spreadsheet_url', models.URLField(blank=True, max_length=500)),
                ('contacts_sheet_name', models.CharField(default='Contacts', max_length=100)),
                ('hot_leads_sheet_name', models.CharField(default='Hot Leads', max_length=100)),
                ('campaign_stats_sheet_name', models.CharField(default='Campaign Stats', max_length=100)),
                ('export_contacts', models.BooleanField(default=True)),
                ('export_hot_leads', models.BooleanField(default=True)),
                ('export_campaign_stats', models.BooleanField(default=True)),
                ('auto_export_interval', models.IntegerField(default=0)),
                ('last_auto_export', models.DateTimeField(blank=True, null=True)),
                ('contact_columns', models.JSONField(default=list)),
                ('hot_lead_columns', models.JSONField(default=list)),
                ('integration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_sheets_config', to='integrations.integration')),
            ],
            options={
                'db_table': 'google_sheets_integrations',
            },
        ),
        migrations.CreateModel(
            name='DiscordIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('webhook_url', models.URLField(max_length=500)),
                ('notify_on_new_contact', models.BooleanField(default=False)),
                ('notify_on_hot_lead', models.BooleanField(default=True)),
                ('notify_on_email_reply', models.BooleanField(default=True)),
                ('notify_on_campaign_complete', models.BooleanField(default=True)),
                ('notify_on_sequence_complete', models.BooleanField(default=False)),
                ('notify_on_form_submit', models.BooleanField(default=True)),
                ('hot_lead_threshold', models.IntegerField(default=80)),
                ('bot_username', models.CharField(default='ColdMail', max_length=80)),
                ('bot_avatar_url', models.URLField(blank=True, max_length=500)),
                ('integration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discord_config', to='integrations.integration')),
            ],
            options={
                'db_table': 'discord_integrations',
            },
        ),
        migrations.CreateModel(
            name='IntegrationFieldMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_field', models.CharField(max_length=100)),
                ('source_field_label', models.CharField(max_length=200)),
                ('target_field', models.CharField(max_length=100)),
                ('target_field_label', models.CharField(max_length=200)),
                ('sync_to_external', models.BooleanField(default=True)),
                ('sync_from_external', models.BooleanField(default=False)),
                ('transform_function', models.CharField(blank=True, max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_mappings', to='integrations.integration')),
            ],
            options={
                'db_table': 'integration_field_mappings',
                'ordering': ['integration', 'order'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10)),
                ('operation', models.CharField(choices=[('sync', 'Sync'), ('export', 'Export'), ('import', 'Import'), ('notification', 'Notification'), ('auth', 'Authentication'), ('test', 'Test')], max_length=20)),
                ('message', models.TextField()),
                ('records_processed', models.IntegerField(default=0)),
                ('records_created', models.IntegerField(default=0)),
                ('records_updated', models.IntegerField(default=0)),
                ('records_failed', models.IntegerField(default=0)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('error_details', models.JSONField(blank=True, default=dict)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='integrations.integration')),
            ],
            options={
                'db_table': 'integration_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesforceIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instance_url', models.URLField(blank=True, max_length=500)),
                ('org_id', models.CharField(blank=True, max_length=50)),
                ('org_name', models.CharField(blank=True, max_length=100)),
                ('sync_direction', models.CharField(choices=[('to_salesforce', 'ColdMail → Salesforce'), ('from_salesforce', 'Salesforce → ColdMail'), ('bidirectional', 'Bidirectional')], default='to_salesforce', max_length=20)),
                ('sync_leads', models.BooleanField(default=True)),
                ('sync_contacts', models.BooleanField(default=True)),
                ('sync_accounts', models.BooleanField(default=False)),
                ('sync_opportunities', models.BooleanField(default=False)),
                ('sync_activities', models.BooleanField(default=True)),
                ('auto_sync_interval', models.IntegerField(default=60)),
                ('last_auto_sync', models.DateTimeField(blank=True, null=True)),
                ('field_mapping', models.JSONField(default=dict)),
                ('sync_only_hot_leads', models.BooleanField(default=False)),
                ('min_score_to_sync', models.IntegerField(default=0)),
                ('create_as_lead', models.BooleanField(default=True)),
                ('integration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salesforce_config', to='integrations.integration')),
            ],
            options={
                'db_table': 'salesforce_integrations',
            },
        ),
        migrations.CreateModel(
            name='SlackIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team_id', models.CharField(blank=True, max_length=50)),
                ('team_name', models.CharField(blank=True, max_length=100)),
                ('default_channel_id', models.CharField(blank=True, max_length=50)),
                ('default_channel_name', models.CharField(blank=True, max_length=100)),
                ('notify_on_new_contact', models.BooleanField(default=False)),
                ('notify_on_hot_lead', models.BooleanField(default=True)),
                ('notify_on_email_reply', models.BooleanField(default=True)),
                ('notify_on_campaign_complete', models.BooleanField(default=True)),
                ('notify_on_sequence_complete', models.BooleanField(default=False)),
                ('notify_on_form_submit', models.BooleanField(default=True)),
                ('notify_on_website_visit', models.BooleanField(default=False)),
                ('hot_lead_threshold', models.IntegerField(default=80)),
                ('integration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slack_config', to='integrations.integration')),
            ],
            options={
                'db_table': 'slack_integrations',
            },
        ),
        migrations.AddIndex(
            model_name='integration',
            index=models.Index(fields=['workspace', 'integration_type'], name='integration_workspa_4fb996_idx'),
        ),
        migrations.AddIndex(
            model_name='integration',
            index=models.Index(fields=['workspace', 'is_active'], name='integration_workspa_d2696f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='integrationfieldmapping',
            unique_together={('integration', 'source_field')},
        ),
        migrations.AddIndex(
            model_name='integrationlog',
            index=models.Index(fields=['integration', '-created_at'], name='integration_integra_9c0fc0_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationlog',
            index=models.Index(fields=['level', '-created_at'], name='integration_level_a3b4be_idx'),
        ),
    ]
