# Generated by Django 5.2.10 on 2026-01-11 07:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Display name for this account', max_length=255)),
                ('email', models.EmailField(help_text='Email address', max_length=254)),
                ('provider', models.CharField(choices=[('smtp', 'SMTP'), ('gmail', 'Gmail (OAuth)'), ('outlook', 'Outlook/Microsoft 365 (OAuth)'), ('sendgrid', 'SendGrid'), ('mailgun', 'Mailgun'), ('aws_ses', 'Amazon SES')], default='smtp', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('error', 'Error'), ('disconnected', 'Disconnected')], default='active', max_length=20)),
                ('smtp_host', models.CharField(blank=True, max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, max_length=255)),
                ('smtp_password', models.CharField(blank=True, max_length=500)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('smtp_use_ssl', models.BooleanField(default=False)),
                ('imap_host', models.CharField(blank=True, max_length=255)),
                ('imap_port', models.IntegerField(default=993)),
                ('imap_username', models.CharField(blank=True, max_length=255)),
                ('imap_password', models.CharField(blank=True, max_length=500)),
                ('imap_use_ssl', models.BooleanField(default=True)),
                ('oauth_access_token', models.TextField(blank=True)),
                ('oauth_refresh_token', models.TextField(blank=True)),
                ('oauth_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('from_name', models.CharField(blank=True, help_text='Display name in From field', max_length=255)),
                ('reply_to', models.EmailField(blank=True, help_text='Reply-to address', max_length=254)),
                ('signature', models.TextField(blank=True, help_text='Email signature HTML')),
                ('daily_limit', models.IntegerField(default=100, help_text='Maximum emails per day')),
                ('hourly_limit', models.IntegerField(default=20, help_text='Maximum emails per hour')),
                ('emails_sent_today', models.IntegerField(default=0)),
                ('emails_sent_this_hour', models.IntegerField(default=0)),
                ('last_hour_reset', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_day_reset', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_warming_up', models.BooleanField(default=False)),
                ('warmup_daily_increase', models.IntegerField(default=5)),
                ('warmup_current_limit', models.IntegerField(default=10)),
                ('warmup_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_connection_test', models.DateTimeField(blank=True, null=True)),
                ('last_connection_success', models.BooleanField(default=False)),
                ('last_connection_error', models.TextField(blank=True)),
                ('last_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('total_emails_sent', models.IntegerField(default=0)),
                ('bounce_rate', models.FloatField(default=0.0)),
                ('reputation_score', models.FloatField(default=100.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_accounts', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_accounts', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'email_accounts',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'email')},
            },
        ),
        migrations.CreateModel(
            name='EmailAccountLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('log_type', models.CharField(choices=[('connection_test', 'Connection Test'), ('email_sent', 'Email Sent'), ('email_failed', 'Email Failed'), ('oauth_refresh', 'OAuth Token Refresh'), ('limit_reached', 'Limit Reached'), ('error', 'Error')], max_length=20)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('is_success', models.BooleanField(default=True)),
                ('email_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='email_accounts.emailaccount')),
            ],
            options={
                'db_table': 'email_account_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
